### ISSUE TITLE
Markdown 문법 설명 자료

### ISSUE THREAD

**Issue by utilForever** [CppKorea/CppConcurrencyInAction#1]
http://blog.kalkin7.com/2014/02/05/wordpress-markdown-quick-reference-for-koreans/

**Comment by akaseon** [comment]
위 링크에는 Markdown 으로 Table 생성하는 법이 안나와 있네요..

아래 링크 가셔서 테이블을 쉽게 만들어 쓰는 법있습니다. 참고 하세요.

http://iamaman.tistory.com/1324

**Comment by Ssangwoo** [comment]
## NAVER - http://www.naver.com/

thstkddn1@naver.com 님께 보내신 메일 <Re: [CppConcurrencyInAction] Markdown 문법 설명 자료 (#1)> 이 다음과 같은 이유로 전송 실패했습니다.

---

받는 사람이 회원님의 메일을 수신차단 하였습니다. 

---
