### ISSUE TITLE
혹시 본 책 관련하여 질문이 있으면 답변해주실분 계신가요?

### ISSUE THREAD

**Issue by junghan0611** [CppKorea/CppConcurrencyInAction#11]
참 아쉽네요. 이런 스터디가 있었다는걸 몰랐어요.
본 책을 틈틈히 읽어보려고 합니다.

아무래도 혼자 보려고 하니 질문 거리가 있을 수 있는데요.
혹시 관련하여 대답을 해주실 멤버가 계신가요? :-) 
가능하시다면 어떻게 소통할 수 있을까요?

**Comment by GiyeonBang** [comment]
안녕하세요. 레포지토리에 관심을 가지고 이슈를 남겨주셔서 감사합니다.
말씀하신 부분은 아래 저희 커뮤니티의 페이스북 그룹을 활용할 수 있습니다.
그 외  C++ Korea의 정보를 받아보실 수 있으니 많은 관심 부탁드립니다.
[C++ Korea 링크](https://www.facebook.com/groups/cppkorea)

**Comment by utilForever** [comment]
궁금한 점 있으시면 여기에 남겨주셔도 좋습니다.
답변이 가능한 질문이라면 친절하게 답변해 드리겠습니다.

**Comment by junghan0611** [comment]
> 토리에 관심을 가지고 이슈를 남겨주셔서 감사합니다.
> 말씀하신 부분은 아래 저희 커뮤니티의 페이스북 그룹을 활용할 수 있습니다.
> 그 외 C++ Korea의 정보를 받아보실 수 있으니 많은 관심 부탁드립니

**Comment by junghan0611** [comment]
@GiyeonBang @utilForever 님 답변 정말 감사합니다. 페이스북 그룹은 가입해서 틈틈히 글을 보고 있습니다. 가능하면 여기 리포에 질문을 남기는게 Concurrency 주제로 정리하기가 좋을 것 같아서요. 되도록이면 여기에 질문을 남기도록 하겠습니다. C++ Korea를 좀 일찍 알았으면 스터디도 참여하고 그럴텐데 아쉽네요. 자료 이렇게 남겨주셔서 진심으로 고맙습니다.
