### ISSUE TITLE
Permission error

### ISSUE THREAD

**Issue by sedman** [CppKorea/CppConcurrencyInAction#2]
git push 하면 다음 에러가 뜨는데 write권한이 없는건가요?

remote: Permission to CppKorea/CppConcurrencyInAction.wiki.git denied to sedman.
fatal: unable to access 'https://github.com/CppKorea/CppConcurrencyInAction.wiki.git/': The requested URL returned error: 403

**Comment by utilForever** [comment]
Contributor 목록에 없어서 오류가 났던 것 같습니다.
추가했으니 pull 할 수 있을 겁니다.
