### ISSUE TITLE
조건변수의 wait 동작에 대해 몇가지 테스트 해 보았습니다.

### ISSUE THREAD

**Issue by akaseon** [CppKorea/CppConcurrencyInAction#5]
조건 변수의 wait 멤버 변수에서 pred 관련 동작이 궁금 하여서 몇가지 테스트를 하여 보았습니다.

template< class Predicate >
void wait( std::unique_lockstd::mutex& lock, Predicate pred );

Listing_C_01.cpp  에서의 큐 부분 입니다.

``` c++
// Our message queue
class queue
{
    std::mutex m;
    std::condition_variable c;
    // Actual queue stores pointer to message_base
    std::queue<std::shared_ptr<message_base> > q;
    public:
    template<typename T>
        void push(T const& msg)
        {
            std::lock_guard<std::mutex> lk(m);
            // Wrap posted message and store pointer
            q.push(std::make_shared<wrapped_message<T> >(msg));
            c.notify_all();
        }

    std::shared_ptr<message_base> wait_and_pop()
    {
        std::unique_lock<std::mutex> lk(m);
        // Block until queue isn't empty
        c.wait(lk,[&]{return !q.empty();});
        auto res=q.front();
        q.pop();
        return res;
    }
};  // class queue
```

테스트 코드 

``` c++
int main( void )
{
    messaging::queue              sQueue;
    std::string                   sPushString( "1234" );
    std::shared_ptr<messaging::message_base>  sPopString;

    sQueue.push( sPushString );
    sPopString = sQueue.wait_and_pop();

    std::cout << ((messaging::wrapped_message<std::string>*)(sPopString.get()))->contents << std::endl;

    return 0;
}
```

제가 생각 하였을때는 wait 함수 내부에서 signal 를 받고 pred 함수의 반환이 true 가 되면 wait 의 block 을 풀어줄것이라고 생각하였는데 실제로는 wait 함수 들어 가면서 pred 함수를 확인해보고 시그널을 대기여부를 판단하는것 같습니다.

그리고 push 함수 안에 실재 데이터 q.push 부분을 지워 주면 signal 이 발생하더라도 wait 함수의 block 은 풀리지 않습니다.

또한 pred 조건을 만족 시키고 signal 을 발생시키지 않으면 wait 을 block 에서 풀리지 않습니다.

``` c++
// 바로 위 테스트 코드 입니다.
// pred 조건을 만족 시키고 signal 을 발생시키지 않으면 wait 을 block 에서 풀리지 않습니다
void t1( messaging::queue   * aQueue )
{
    std::string                   sPushString( "1234" );

    while( gContinue == 1 )
    {
    }

    sleep( 5 );

    std::cout << "Push : " << sPushString << std::endl;

    aQueue->push( sPushString );

}

void t2( messaging::queue   * aQueue )
{
    std::shared_ptr<messaging::message_base>  sPopString;

    gContinue = 1;

    std::cout << "wait Pop" << std::endl;

    sPopString = aQueue->wait_and_pop();

    std::cout << ((messaging::wrapped_message<std::string>*)(sPopString.get()))->contents << std::endl;
}

int main( void )
{
    messaging::queue              sQueue;
    gContinue = 0;

    std::thread thread1( t1, &sQueue );
    std::thread thread2( t2, &sQueue );

    thread1.join();
    thread2.join();


    return 0;
}
```

그래서 결론은 wait 함수의 동작은 아래 정도로 정리 할수 있을것 같습니다.
1. block 들어 가기전 pred 함수가 정의되어 있으면 조건을 검사 한다.
2. 조건이 참이면 block 으로 들어가서 signal를 대기 하지 않고 wait 함수가 반환된다.
3. 조건이 거짓이면 block 으로 들어가서 signal 를 대기 한다.
4. 이때 pred 함수가 참이 되는 조건이 발생되어도 block 상태에서 깨어나지 않는다.
5. signal 이 발생하면 block 상태에서 깨어난다. 

아까 luncliff 님에게 signal Lost 가 발생 할것 같다라고 말씀 드렸었는데
2번 항목때문에 signal Lost 를 발생하지 않습니다. 
c++11 이전에는 2번 부분을 감안해서 코딩해 줘야 했었는데 언어 자체에서 지원해주네요..

**Comment by luncliff** [comment]
제가 책을 중심으로 내용을 구성하다보니 이런 부분을 미처 보지 못한 것 같네요.  
저도 올려주신 것을 보고레퍼런스를 검색 해봤는데, `wait(lck, pred)`와 같은 호출은 아래와 같이 동작한다고 합니다.

``` C++
while (!pred()) {
    wait(lock);
}
```

이런 코드라면 말씀하신대로 동작하는 이유를 알 수 있을 것 같네요.

http://en.cppreference.com/w/cpp/thread/condition_variable/wait

**Comment by akaseon** [comment]
레퍼런스 봤었는데 자세히 안봐서 그냥 지나쳤네요 ㅠ_ㅠ

네 luncliff 님이 올려주신대로 pred 검사 하고 wait 으로 들어 가기때문에 2번 항목이 문제가 안됩니다.

**Comment by akaseon** [comment]
wait 함수에 pred 함수를 넘겨 주면 Spurious Wakeup 이 나타나지 않을수 있지 않을까요?
 wait 에서 block 이 풀렸지만 다시 pred 조건을 확인하니깐요?

**Comment by luncliff** [comment]
아, 늦게 봤네요.
spurious wakeup 자체를 프로그램에서 막을 방법은 없으니, 혹시나 활성화 되더라도 predicate를 검사해서 '안전하게' 다시 잠들도록 하는 방법이라고 생각되네요.

**Comment by akaseon** [comment]
충분히 공유 되었을거라 생각하고 닫겠습니다.
